# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_a', '0002_auto_20170704_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_a.Direction'),
        ),
    ]
